# Generated by Django 6.0.2 on 2026-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
