# Generated by Django 6.0.2 on 2026-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_issue_priority_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('road', 'Road Issues'), ('water', 'Water Issues'), ('electricity', 'Electricity Issues'), ('sanitation', 'Sanitation Issues'), ('public_safety', 'Public Safety'), ('other', 'Other')], max_length=50),
        ),
    ]
